### ISSUE TITLE
Doesn't work with punctuation 

### ISSUE THREAD

**Issue by fedorthedev** [gonzoknows/AI-Detection-Bypassers#1]
If I have punctuation in my text, python gives me a syntax error and won't let me use the script

**Comment by gonzoknows** [comment]
I'll check it out, go ahead and just use this for now 
https://gonzoknows.com/posts/Bypass-AI-Detection-Using-Different-Fonts/

**Comment by MazeCow** [comment]
> If I have punctuation in my text, python gives me a syntax error and won't let me use the script

Use the program in my AI-Detector-Bypass repo. It uses a similar method as this one but works with punctuation, doesn't break the font, and it doesn't trigger spellcheck.

**Comment by gonzoknows** [comment]
New bot is out https://gonzoknows.com/posts/Bypass-AI-Detection-Bot-Method-1/.
